commons/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index),
]

mangoplants/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('commons.urls')),
    path('posts/', include('posts.urls')),
    path('plants/', include('plants.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

plants/urls.py
from django.urls import path
from . import views

app_name = 'plants'

urlpatterns = [
    path('', views.plant_list, name='plant_list'),
    path('<int:pk>/', views.plant_detail, name='plant_detail'),
    path('new/', views.plant_create, name='plant_create'),
    path('<int:pk>/edit', views.plant_update, name='plant_update'),
    path('<int:pk>/delete', views.plant_delete, name='plant_delete'),
]

posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.posts, name='posts'),
    path('<int:pk>/', views.post_detail, name='post_detail'),
    path('new/', views.post_create, name='post_create'),
    path('<int:pk>/edit', views.post_update, name='post_update'),
    path('<int:pk>/delete', views.post_delete, name='post_delete'),
]

accounts/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    pass

commons/models.py
from django.db import models

# Create your models here.

plants/models.py
from django.utils import timezone
from django.db import models
from django.conf import settings

from commons.utils import uuid_name_upload_to


class Plant(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True, blank=True)
    name = models.CharField(max_length=20)
    photo = models.ImageField(upload_to=uuid_name_upload_to)
    note = models.TextField(default='')
    last_water = models.DateField(null=True, blank=True)
    joined = models.DateField(null=True, blank=True)
    created_at = models.DateField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

    @property
    def passed_date(self):
        now_date = timezone.now().date()
        if not self.last_water:
            return
        return (now_date - self.last_water).days

    @property
    def since_date(self):
        now_date = timezone.now().date()
        if not self.joined:
            return
        return (now_date - self.joined).days

posts/models.py
from django.db import models
from django.conf import settings

from commons.utils import uuid_name_upload_to


class Post(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True, blank=True)
    plant = models.ForeignKey('plants.Plant', on_delete=models.CASCADE)
    photo = models.ImageField(upload_to=uuid_name_upload_to)
    content = models.TextField()
    created_at = models.DateField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.content

plants/forms.py
from django import forms
from .models import Plant


class PlantForm(forms.ModelForm):
    class Meta:
        model = Plant
        exclude = ['user']

posts/forms.py
from django import forms

from .models import Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        exclude = ['user']

accounts/views.py
from django.shortcuts import render

# Create your views here.

commons/views.py
from django.shortcuts import render

from plants.models import Plant
from posts.models import Post


def index(request):
    plant_qs = Plant.objects.all()
    post_qs = Post.objects.all()
    context = {
        'plants': plant_qs,
        'posts': post_qs
    }
    return render(request, 'commons/index.html', context=context)

plants/views.py
from django.shortcuts import render, redirect
from .models import Plant
from .forms import PlantForm


def plant_list(request):
    plants = Plant.objects.all()
    return render(request, 'plants/plant_list.html', {'plants': plants})


def plant_detail(request, pk):
    return render(request, 'plants/plant_detail.html', {'plant': Plant.objects.get(pk=pk)})


def plant_create(request):
    if request.method == 'POST':
        plant_form = PlantForm(request.POST, request.FILES)
        if plant_form.is_valid():
            plant_form.save()
            return redirect('plants:plant_list')
    else:
        plant_form = PlantForm()
    return render(request, 'plants/plant_form.html', {'form': plant_form})


def plant_update(request, pk):
    plant = Plant.objects.get(pk=pk)
    if request.method == 'POST':
        plant_form = PlantForm(request.POST, request.FILES, instance=plant)
        if plant_form.is_valid():
            plant_form.save()
            return redirect('plants:plant_detail', pk=plant.pk)
    else:
        plant_form = PlantForm(instance=plant)
    return render(request, 'plants/plant_form.html', {'form': plant_form})


def plant_delete(request, pk):
    if request.method == 'POST':
        plant = Plant.objects.get(pk=pk)
        plant.delete()
        return redirect('plants:plant_list')
    else:
        return render(request, 'posts/post_confirm_delete.html')

posts/views.py
from django.shortcuts import render, redirect
from .models import Post
from .forms import PostForm


def posts(request):
    post_qs = Post.objects.all()
    return render(request, 'posts/post_list.html', context={'post_qs': post_qs})


def post_detail(request, pk):
    post = Post.objects.get(pk=pk)
    return render(request, 'posts/post_detail.html', context={'post': post})


def post_create(request):
    if request.method == 'POST':
        post_form = PostForm(request.POST, request.FILES)
        if post_form.is_valid():
            new_post = post_form.save()
            return redirect('posts:post_detail', pk=new_post.id)
    else:
        post_form = PostForm()
    return render(request, 'posts/post_form.html', {'form': post_form})


def post_update(request, pk):
    post = Post.objects.get(id=pk)
    if request.method == 'POST':
        # request.POST: 수정할 내용, instance인자: 수정 대상 지정
        post_form = PostForm(request.POST, request.FILES, instance=post)
        if post_form.is_valid():
            post_form.save()
            return redirect('posts:post_detail', pk=post.id)
    else:
        post_form = PostForm(instance=post)  # post데이터가 form에 바운드된 상태로 데이터가 생성된다.
    return render(request, 'posts/post_form.html', {'form': post_form})


def post_delete(request, pk):
    post = Post.objects.get(id=pk)
    if request.method == 'POST':
        post.delete()
        return redirect('posts:posts')
    else:
        return render(request, 'posts/post_confirm_delete.html')

commons/templates/commons/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">
<head>
  <meta charset="UTF-8">
  <meta name="viewport"
        content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>망고플랜트s</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">
  <link rel="stylesheet" href="{% static 'commons/css/base.css' %}">
  {% block css %}
  {% endblock css %}
</head>
<body>
<nav class="navbar navbar-expand-md navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'commons:home' %}"><h1>망고 플랜트s</h1></a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup"
            aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav">
        <a class="nav-link active" href="{% url 'commons:home' %}">Home</a>
{#        <a class="nav-link" href="page1.html">식물도감</a>#}
        <a class="nav-link" href="{% url 'plants:plant_list' %}">내 식물</a>
        <a class="nav-link" href="{% url 'posts:posts' %}">식물일기</a>
      </div>
    </div>
  </div>
</nav>
{% block container %}
{% endblock container %}
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-U1DAWAznBHeqEIlVSCgzq+c9gqGAJn5c/t99JyeKa9xxaYpSvHU5awsuZVVFIhvj"
        crossorigin="anonymous"></script>
</body>
</html>

commons/templates/commons/index.html
{% extends 'commons/base.html' %}
{% load static %}
{% block css %}
  <link rel="stylesheet" href="{% static 'commons/css/index.css' %}" type="text/css">
{% endblock css %}
{% block container %}
  <div class="container">
    <a href="{% url 'plants:plant_list' %}"><h3>My plants</h3></a>
    <div class="row">
      <ul>
        {% for plant in plants %}
          <li>
            <a href="{% url 'plants:plant_detail' plant.pk %}">
              <div class="plant">
                <div class="plant-avatar"
                     style="background-image: url('{% get_media_prefix %}{{ plant.photo }}');"></div>
                <p>{{ plant.name }}</p>
              </div>
            </a>
          </li>
        {% endfor %}
      </ul>
    </div>
    <a href="{% url 'posts:posts' %}"><h3>My Story</h3></a>
    <div class="row">
      {% for post in posts %}
        <div class="col-6 story-item">
          <a href="{% url 'posts:post_detail' post.pk %}">
            <div class="card-image" style="background-image: url('{% get_media_prefix %}{{ post.photo }}');"></div>
            <h6>{{ post.plant.name }}</h6>
            <p class="card-text">{{ post.content|truncatechars:15 }}</p>
          </a>
        </div>
      {% endfor %}
    </div>
  </div>
{% endblock container %}

plants/templates/plants/plant_detail.html
{% extends 'commons/base.html' %}
{% load static %}
{% block css %}
  <style>
      .plant-photo {
          width: 50%;
          height: 50%;
          padding-bottom: 50%;
          background-color: bisque;
          border-radius: 100%;
          background-size: cover;
          background-repeat: no-repeat;
          background-position: center center;
          display: inline-block;
      }

      .card {
          border-radius: 20px;
          background-color: beige;
          border: none;
      }

      a {
          text-decoration: none;
          color: black;
      }

      .icon-container a {
          margin-right: 10px;
      }
  </style>
{% endblock %}
{% block container %}
  <div class="container">
    <div class="row mb-3">
      <div class="col-10">
        <a href="{% url 'plants:plant_list' %}"><h3>My plants</h3></a>
      </div>
    </div>
    <div class="row mb-2">
      <div class="d-flex justify-content-center">
        <div class="plant-photo" style="background-image: url('{% get_media_prefix %}{{ plant.photo }}');"></div>
      </div>
    </div>
    <div class="row mb-4">
      <div class="text-center" style="font-size: 1.25em;">{{ plant }}</div>
    </div>
    <div class="row mb-2">
      <div class="col-12">
        <div class="icon-container d-flex flex-row-reverse" style="margin-bottom: 20px;">
          <a href="{% url 'plants:plant_update' plant.pk %}"><img src="{% static 'commons/icon/pencil-square.svg' %}"
                                                                  alt="" style="width: 25px;"></a>
          <a href="{% url 'plants:plant_delete' plant.pk %}"><img src="{% static 'commons/icon/x-circle.svg' %}" alt=""
                                                                  style="width: 25px;"></a>
        </div>
      </div>
    </div>
    <div class="row mb-2">
      <div class="col">
        <div class="card">
          <div class="card-body">
            <h5 class="card-title">Notification</h5>
            <hr>
            <p>{{ plant.name }}과 함께한지 {{ plant.since_date }}일 지났어요.</p>
            <p>마지막으로 물을 준지는 {{ plant.passed_date }}일 됬네요</p>
          </div>
        </div>
      </div>
    </div>
    <div class="row mb-2">
      <div class="col">
        <div class="card" style="background-color: #FFFACD; border: none">
          <div class="card-body text-center" style="height: 250px; float: left">
            <br>
            <hr style="color: red;">
            {% if plant.note %}
              {{ plant.note }}
            {% else %}
              <br>
              <p>노트를 이용하여 나만의 가드닝 정보를 기록해보세요</p>
              <br>
              <button type="button" class="btn btn-outline-success">노트 작성하기</button>
            {% endif %}
          </div>
        </div>
      </div>
    </div>

  </div>
{% endblock %}

plants/templates/plants/plant_form.html
{% extends 'commons/base.html' %}
{% load static %}
{% block css %}
{% endblock %}
{% block container %}
  <div class="container">
    <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Submit">
</form>
  </div>
{% endblock %}

plants/templates/plants/plant_list.html
{% extends 'commons/base.html' %}
{% load static %}
{% block css %}
  <link rel="stylesheet" href="{% static 'posts/css/post_list.css' %}" type="text/css">
  <style>
      .plant-photo {
          width: 95%;
          height: 95%;
          padding-bottom: 95%;
          background-color: bisque;
          border-radius: 100%;
          background-size: cover;
          background-repeat: no-repeat;
          background-position: center center;
          display: inline-block;
      }
      a {
          text-decoration: none;
          color: black;
      }
  </style>
{% endblock css %}
{% block container %}
  <div class="container">
    <div class="row mb-3">
      <div class="col-10">
        <a href="{% url 'plants:plant_list' %}"><h3>My plants</h3></a>
      </div>
      <div class="col-2" style="line-height: 50px;">
        <a href="{% url 'plants:plant_create' %}" style="vertical-align: center">
          <img src="{% static 'commons/icon/plus-circle-fill.svg' %}" style="width: 30px;">
        </a>
      </div>
    </div>
    {% for plant in plants %}
      <a href="{% url 'plants:plant_detail' plant.pk %}">
      <div class="row mb-4 px-2">
        <div class="col-5">
          <div class="plant-photo" style="background-image: url('{% get_media_prefix %}{{ plant.photo }}');"></div>
        </div>
        <div class="col-6">
          <table style="height: 120px;">
            <tbody>
            <tr style="font-size: 1.25em;">
              <td class="align-middle">{{ plant.name }}<br>
                <div class="badge bg-success">D+{{ plant.passed_date }}</div>
              </td>
            </tr>
            </tbody>
          </table>
        </div>
      </div>
      </a>
    {% endfor %}
  </div>
{% endblock container %}

posts/templates/posts/post_confirm_delete.html
{% extends 'commons/base.html' %}
{% load static %}
{% block css %}
{% endblock %}
{% block container %}
  <div class="container">
    <p>정말 삭제하시겠습니까?</p>
    <form method="POST">{% csrf_token %}
        <input type="submit" value="삭제하기" class="btn btn-outline-danger">
    </form>
  </div>
{% endblock %}

posts/templates/posts/post_detail.html
{% extends "commons/base.html" %}
{% load static %}
{% block css %}
  <style>
      .post-photo {
          float: left;
          background-color: aqua;
          padding-bottom: 100%;
          width: 100%;
          height: 100%;
          margin-bottom: 15px;
          background-size: cover;
          background-repeat: no-repeat;
          background-position: center center;
      }

      .plant-photo {
          width: 20%;
          height: 20%;
          padding-bottom: 20%;
          background-color: bisque;
          border-radius: 100%;
          margin-bottom: 15px;
          background-size: cover;
          background-repeat: no-repeat;
          background-position: center center;
      }

      .icon-container a {
          text-decoration: none;
          color: black;
          margin-right: 10px;
      }

      .form-control:focus {
        outline: none;
        box-shadow: none;
      }
  </style>
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.4/css/all.css"
        integrity="sha384-DyZ88mC6Up2uqS4h/KRgHuoeGwBcD4Ng9SiP4dIRy0EXTlnuz47vAwmeGwVChigm" crossorigin="anonymous">
{% endblock %}
{% block container %}
  <div class="container-fluid">
    <div class="row" style="margin-top: 20px;">
      <div class="col-10">
        <div class="plant-photo float-start" style="background-image: url('{% get_media_prefix %}{{ post.plant.photo }}');"></div>
      </div>
    </div>
    <div class="row">
      <div class="post-photo" style="background-image: url('{% get_media_prefix %}{{ post.photo }}');"></div>
    </div>
    <div class="row">
      <div class="col-12">
        <div class="icon-container" style="margin-bottom: 20px;">
          <a href="#"><img src="{% static 'commons/icon/heart.svg' %}" style="width: 25px;"></a>
          <a href="{% url 'posts:post_update' post.pk %}"><img src="{% static 'commons/icon/pencil-square.svg' %}" alt="" style="width: 25px;"></a>
          <a href="{% url 'posts:post_delete' post.pk %}"><img src="{% static 'commons/icon/x-circle.svg' %}" alt="" style="width: 25px;"></a>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-12" style="margin-bottom: 10px;">
        {{ post.content }}
      </div>
    </div>
    <div class="row">
      <div class="col-12">
      <form class="" style="border: 1px solid gray; border-radius: 20px;">
          <label for="comment" class="visually-hidden">comment</label>
          <input type="text" class="form-control" id="comment" placeholder="댓글 입력" style="width: 80%; display: inline-block; border: none; border-radius: 20px;">
          <button type="submit" class="" style="border: none; background-color: rgba( 255, 255, 255, 0 );">Send</button>
      </form>
      </div>
    </div>
  </div>
{% endblock container %}

posts/templates/posts/post_form.html
{% extends 'commons/base.html' %}
{% load static %}
{% block css %}
{% endblock %}
{% block container %}
  <div class="container">
    <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Submit">
</form>
  </div>
{% endblock %}

posts/templates/posts/post_list.html
{% extends 'commons/base.html' %}
{% load static %}
{% block css %}
  <link rel="stylesheet" href="{% static 'posts/css/post_list.css' %}" type="text/css">
{% endblock css %}
{% block container %}
  <div class="container">
    <div class="row">
      <div class="col-10"><h3>My plant Story</h3></div>
      <div class="col-2" style="line-height: 50px;">
        <a href="{% url 'posts:post_create' %}" style="vertical-align: center">
          <img src="{% static 'commons/icon/plus-circle-fill.svg' %}" style="width: 30px;">
        </a>
      </div>
    </div>
    <div class="row">
      {% for post in post_qs %}
        <div class="col-12 story">
          <a href="{% url 'posts:post_detail' post.id %}">
          <div class="story-image" style="background-image: url('{% get_media_prefix %}{{ post.photo }}');"></div>
          </a>
          <div class="icon-container">
            <a href="#">
              <img src="{% static 'commons/icon/chat.svg' %}" alt="" style="width: 20px;">
            </a>1
            <a href="#">
              <img src="{% static 'commons/icon/heart.svg' %}" alt="" style="width: 20px;">
            </a>2
          </div>
          <div class="content">{{ post.content|linebreaks }}</div>
          <div>ㄴ 댓글맨1: 기능 추가 예정1</div>
          <div>ㄴ 댓글맨2: 기능 추가 예정2</div>
        </div>
      {% endfor %}
    </div>
  </div>
{% endblock container %}